version: '3.8'

services:
    nginx:
        image: nginx:alpine
        ports:
            - "${APP_PORT:-5080}:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        environment:
            PHP_IDE_CONFIG: "serverName=docker-symfony"
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    mysql:
        image: mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "${DB_OUTER_PORT:-5006}:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql

    redis:
        image: redis:alpine
        ports:
            - "${REDIS_OUTER_PORT:-5079}:6379"
